# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a85168cd2da3407f65ac23b4320e896"
name = "remix-chat-tutorial"
handle = "remix-chat-tutorial"
application_url = "https://linux-reporters-prepare-billion.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cart-snapshot.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://linux-reporters-prepare-billion.trycloudflare.com/auth/callback",
  "https://linux-reporters-prepare-billion.trycloudflare.com/auth/shopify/callback",
  "https://linux-reporters-prepare-billion.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
